<a href="https://colab.research.google.com/github/RonakornST/AI_For_Engineers/blob/main/OpenAIGym(Custom_Environment).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://www.faststreamtech.com/wp-content/uploads/2021/06/IoT-based-smart-shower.jpg)

In [ ]:
# Enviroment: Smart Shower
# Optimal temparature between 37 and 39 degrees
# Shower Length : 60 seconds
# Action : turn down, leave, turn up
# Build a model that keep the optimal range for as long as possible

In [ ]:
#Import library
import gym
from gym.spaces import Discrete, Box
import numpy as np
import random
import plotly.graph_objs as go


In [ ]:
class ShowerEnv():
    def __init__(self):
        # Actions we can take, down, stay, up
        self.action_space = Discrete(3)
        # Temperature array
        self.observation_space = Box(low=np.array([0]), high=np.array([100]))
        # Set start temp
        self.state = 45 + random.randint(-3,3)
        # Set shower length
        self.shower_length = 60

    def step(self, action):
        # Apply action
        # 0 -1 = -1 temperature
        # 1 -1 = 0
        # 2 -1 = 1 temperature
        self.state += action -1
        # Reduce shower length by 1 second
        self.shower_length -= 1

        # Calculate reward
        if self.state >=37 and self.state <=39:
            reward =1
        else:
            reward = -1

        # Check if shower is done
        if self.shower_length <= 0:
            done = True
        else:
            done = False

        # Apply temperature noise
        #self.state += random.randint(-1,1)
        # Set placeholder for info
        info = {}

        # Return step information
        return self.state, reward, done, info

    def render(self):
        # Implement viz
        pass

    def reset(self):
        # Reset shower temperature
        self.state = 45 + random.randint(-3,3)
        # Reset shower time
        self.shower_length = 60
        return self.state

In [ ]:
env = ShowerEnv()

/usr/local/lib/python3.8/dist-packages/gym/spaces/box.py:128: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


In [ ]:
state = env.reset()
print("(start)")
while True:
  action = env.action_space.sample() # random action
  state, reward, done, info  = env.step(action) #take action to enviroment
  print(f'Action = {action}, State = {state}, Reward = {reward}, Done = {done}')
  if done:
    break;

(start)
Action = 2, State = 48, Reward = -1, Done = False
Action = 2, State = 49, Reward = -1, Done = False
Action = 0, State = 48, Reward = -1, Done = False
Action = 2, State = 49, Reward = -1, Done = False
Action = 0, State = 48, Reward = -1, Done = False
Action = 0, State = 47, Reward = -1, Done = False
Action = 2, State = 48, Reward = -1, Done = False
Action = 1, State = 48, Reward = -1, Done = False
Action = 2, State = 49, Reward = -1, Done = False
Action = 0, State = 48, Reward = -1, Done = False
Action = 0, State = 47, Reward = -1, Done = False
Action = 1, State = 47, Reward = -1, Done = False
Action = 0, State = 46, Reward = -1, Done = False
Action = 2, State = 47, Reward = -1, Done = False
Action = 2, State = 48, Reward = -1, Done = False
Action = 1, State = 48, Reward = -1, Done = False
Action = 2, State = 49, Reward = -1, Done = False
Action = 1, State = 49, Reward = -1, Done = False
Action = 1, State = 49, Reward = -1, Done = False
Action = 1, State = 49, Reward = -1, Done 

In [ ]:
#Create initial Q-Table
Q = np.zeros([100,env.action_space.n])
print(Q.shape)
print(Q)

(100, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0.

In [ ]:
#Set hyperparameters
learning_rate = 0.1
gamma = 0.8
episodes = 70

In [ ]:
# Q-learning
reward_list = []

for i in range(episodes):
  state = env.reset()
  sum_reward = 0
  while True:
    action = np.argmax(Q[state,:])# + np.random.randn(1, env.action_space.n)*(1./(i+1)))

    next_state, reward, done, info = env.step(action)
    Q[state,action] = Q[state,action] + learning_rate*(reward+gamma*np.max(Q[next_state,:]))

    sum_reward = sum_reward+reward
    state = next_state


    if done == True:
      break

  reward_list.append(sum_reward)

In [ ]:
#Plot total reward
h = go.Scatter(y=reward_list, mode='lines', line = dict(width=2,color='red'))
data = [h]
layout = go.Layout(title='Total Reward', xaxis = dict(title ='Epochs'),yaxis=dict(title=''))
fig = go.Figure(data = data, layout=layout)
fig.show(renderer='colab')

In [ ]:
print(Q)

[[-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+00  0.00000000e+00]
 [-1.00000000e-01  0.00000000e+

In [ ]:
#Inference
state = env.reset()
print("(start)")
while True:
  action = np.argmax(Q[state,:]) # random action
  state, reward, done, info  = env.step(action) #take action to enviroment
  print(f'Action = {action}, State = {state}, Reward = {reward}, Time-length = {env.shower_length}, Done = {done}')
  if done:
    break;

(start)
Action = 0, State = 42, Reward = -1, Time-length = 59, Done = False
Action = 0, State = 41, Reward = -1, Time-length = 58, Done = False
Action = 0, State = 40, Reward = -1, Time-length = 57, Done = False
Action = 0, State = 39, Reward = 1, Time-length = 56, Done = False
Action = 0, State = 38, Reward = 1, Time-length = 55, Done = False
Action = 0, State = 37, Reward = 1, Time-length = 54, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 53, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 52, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 51, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 50, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 49, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 48, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 47, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 46, Done = False
Action = 1, State = 37, Reward = 1, Time-length = 4